// payloads-builds/react/pages-seed/src/pages/Dashboard.tsx
const Dashboard = () => {
  const stats = [
    { label: 'Total Users', value: '1,234', change: '+12%' },
    { label: 'Revenue', value: '$45,678', change: '+8%' },
    { label: 'Orders', value: '567', change: '+5%' },
    { label: 'Growth', value: '23%', change: '+3%' },
  ]

  return (
    <div className="min-h-screen py-16 bg-gray-50">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold mb-8">Dashboard</h1>
        
        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {stats.map((stat, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow">
              <div className="text-sm text-gray-500 mb-2">{stat.label}</div>
              <div className="text-3xl font-bold text-gray-800 mb-1">
                {stat.value}
              </div>
              <div className="text-sm text-green-600">{stat.change}</div>
            </div>
          ))}
        </div>

        {/* Dashboard Content */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-2xl font-semibold mb-4">Recent Activity</h2>
            <p className="text-gray-600">Dashboard activity content goes here</p>
          </div>

          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-2xl font-semibold mb-4">Quick Actions</h2>
            <div className="space-y-2">
              <button className="w-full bg-primary-600 text-white py-2 rounded-lg hover:bg-primary-700 transition">
                Action One
              </button>
              <button className="w-full bg-primary-600 text-white py-2 rounded-lg hover:bg-primary-700 transition">
                Action Two
              </button>
              <button className="w-full bg-primary-600 text-white py-2 rounded-lg hover:bg-primary-700 transition">
                Action Three
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Dashboard

// payloads-builds/vue/dashboard-seed/src/views/Dashboard.vue
<template>
  <div>
    <h1 class="text-3xl font-bold mb-6 text-gray-800 dark:text-white">Dashboard</h1>
    
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
      <div
        v-for="stat in stats"
        :key="stat.label"
        class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow"
      >
        <div class="text-sm text-gray-500 dark:text-gray-400">{{ stat.label }}</div>
        <div class="text-2xl font-bold text-gray-800 dark:text-white mt-2">
          {{ stat.value }}
        </div>
      </div>
    </div>

    <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
      <h2 class="text-xl font-semibold mb-4 text-gray-800 dark:text-white">Recent Activity</h2>
      <p class="text-gray-600 dark:text-gray-400">Dashboard content goes here...</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const stats = ref([
  { label: 'Total Users', value: '1,234' },
  { label: 'Revenue', value: '$45,678' },
  { label: 'Orders', value: '567' },
  { label: 'Growth', value: '+12%' },
])
</script>
