// payloads-builds/react/pages-seed/src/App.tsx
import { Outlet } from 'react-router-dom'
import Header from './components/Layout/Header'
import Footer from './components/Layout/Footer'

const App = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1">
        <Outlet />
      </main>
      <Footer />
    </div>
  )
}

export default App

// payloads-builds/vue/dashboard-seed/src/App.vue
<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900">
    <div class="flex">
      <!-- Sidebar -->
      <Sidebar />
      
      <!-- Main Content -->
      <div class="flex-1 flex flex-col">
        <AppHeader />
        <main class="flex-1 p-6">
          <router-view />
        </main>
      </div>
    </div>
  </div>
</template>

<script setup>
import Sidebar from './components/Sidebar/Sidebar.vue'
import AppHeader from './components/Header/AppHeader.vue'
</script>

<style scoped>
/* Component styles */
</style>
